spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # generate-ddl: false
    show-sql: true
    hibernate:
      # 自动建表
      ddl-auto: update
    datasource:
      username: bLive_user
      password: bLive_user!@#_456
      url: jdbc:h2:./.data/bLive;AUTO_SERVER=TRUE
      driver-class-name: org.h2.Driver
    h2:
      console:
        path: /h2-console/easyNginx
        enabled: true
        settings:
          web-allow-others: true
          web-admin-password: EasyNginx@123
    # 配置时间格式化
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
      default-property-inclusion: non_null
    sql:
      init:
        schema-locations: classpath*:/database/schema/schema.sql
        #        data-locations: classpath*:/database/data/data.sql
        continue-on-error: true
        mode: always
        platform: H2
        encoding: UTF-8
        password: EasyNginx@123
        username: EasyNginx
